<?php
require_once '../config.php';
require_once '../functions.php';

date_default_timezone_set('Asia/Kuala_Lumpur');

// Check authentication
session_start();
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'Admin') {
    header('Location: ../login.php');
    exit;
}

// Get users
$users = [];
$sql = "SELECT UserID, Username, Email, Role, AccountStatus, CreatedAt FROM user ORDER BY UserID";
$result = $conn->query($sql);
if ($result) {
    while ($row = $result->fetch_assoc()) {
        $users[] = $row;
    }
}

// Count user types
$totalUsers = count($users);
$activeUsers = 0;
$suspendedUsers = 0;
foreach ($users as $user) {
    if ($user['AccountStatus'] === 'Active') {
        $activeUsers++;
    } else {
        $suspendedUsers++;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Management Report - TrafAnalyz</title>
    <style>
        /* Regular styles */
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 { 
            text-align: center;
            color: #333;
        }
        .header-info {
            text-align: right;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .stats {
            margin: 20px 0;
        }
        .stat-item {
            margin: 5px 0;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            font-style: italic;
            text-align: center;
        }
        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
        }
        .badge-active {
            background-color: #d4edda;
            color: #155724;
        }
        .badge-suspended {
            background-color: #f8d7da;
            color: #721c24;
        }
        .non-print {
            margin: 20px 0;
            padding: 15px;
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .btn {
            padding: 8px 15px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }
        .btn:hover {
            background-color: #45a049;
        }

        /* Print-specific styles */
        @media print {
            .non-print {
                display: none;
            }
            body {
                margin: 0;
                padding: 15px;
            }
            table {
                page-break-inside: auto;
            }
            tr {
                page-break-inside: avoid;
                page-break-after: auto;
            }
        }
    </style>
</head>
<body>
    <div class="non-print">
        <h2>User Management Report - Print View</h2>
        <p>This page is formatted for printing. Use your browser's print function (Ctrl+P or Cmd+P) to print or save as PDF.</p>
        <button class="btn" onclick="window.print();">Print / Save as PDF</button>
        <a class="btn" href="admin_users.php" style="background-color: #6c757d;">Back to User Management</a>
    </div>

    <h1>TrafAnalyz User Management Report</h1>
    
    <div class="header-info">
        <p>Generated on: <?php echo date('Y-m-d H:i:s'); ?></p>
        <p>Generated by: <?php echo isset($_SESSION['username']) ? $_SESSION['username'] : 'Administrator'; ?></p>
    </div>
    
    <div class="stats">
        <h2>User Statistics</h2>
        <div class="stat-item"><strong>Total Users:</strong> <?php echo $totalUsers; ?></div>
        <div class="stat-item"><strong>Active Users:</strong> <?php echo $activeUsers; ?></div>
        <div class="stat-item"><strong>Suspended Users:</strong> <?php echo $suspendedUsers; ?></div>
    </div>
    
    <h2>User Accounts</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $user['UserID']; ?></td>
                <td><?php echo htmlspecialchars($user['Username']); ?></td>
                <td><?php echo htmlspecialchars($user['Email']); ?></td>
                <td><?php echo $user['Role']; ?></td>
                <td>
                    <span class="badge badge-<?php echo strtolower($user['AccountStatus']); ?>">
                        <?php echo $user['AccountStatus']; ?>
                    </span>
                </td>
                <td><?php echo date('Y-m-d', strtotime($user['CreatedAt'])); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report contains confidential information and is for authorized personnel only.</p>
        <p>TrafAnalyz System - <?php echo date('Y'); ?></p>
    </div>
</body>
</html>