<?php
require_once '../auth/admin_auth.php'; // Admin Login Validation
require_once '../config.php';
require_once '../functions.php';

date_default_timezone_set('Asia/Kuala_Lumpur');

// Log export to database if coming from export action
if (isset($_GET['export']) && $_GET['export'] == '1') {
    $userId = $_SESSION['user_id'] ?? null;
    
    if ($userId) {
        $exportType = 'PDF';
        $currentDate = date('Y-m-d');
        $description = "Admin exported user management report as PDF - $currentDate";
        
        $stmt = $conn->prepare("INSERT INTO export_history (UserID, ExportType, ExportedDataDescription) VALUES (?, ?, ?)");
        $stmt->bind_param("iss", $userId, $exportType, $description);
        $stmt->execute();
    }
}

// Get users
$users = [];
$sql = "SELECT UserID, Username, Email, Role, AccountStatus, CreatedAt FROM user ORDER BY UserID";
$result = $conn->query($sql);
if ($result) {
    while ($row = $result->fetch_assoc()) {
        $users[] = $row;
    }
}

// Count user types
$totalUsers = count($users);
$activeUsers = 0;
$suspendedUsers = 0;
foreach ($users as $user) {
    if ($user['AccountStatus'] === 'Active') {
        $activeUsers++;
    } else {
        $suspendedUsers++;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Management Report - TrafAnalyz</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="admin_style.css">
    <style>
        /* Regular styles */
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 { 
            text-align: center;
            color: #333;
        }
        .header-info {
            text-align: right;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .stats {
            margin: 20px 0;
        }
        .stat-item {
            margin: 5px 0;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            font-style: italic;
            text-align: center;
        }
        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
        }
        .badge-active {
            background-color: #d4edda;
            color: #155724;
        }
        .badge-suspended {
            background-color: #f8d7da;
            color: #721c24;
        }
        .non-print {
            margin: 20px 0;
            padding: 15px;
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .btn {
            padding: 8px 15px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }
        .btn:hover {
            background-color: #45a049;
        }

        /* Print-specific styles */
        @media print {
            .non-print {
                display: none;
            }
            body {
                margin: 0;
                padding: 15px;
            }
            table {
                page-break-inside: auto;
            }
            tr {
                page-break-inside: avoid;
                page-break-after: auto;
            }
        }
    </style>
</head>
<body>
    <div class="non-print">
        <h2>User Management Report - Print View</h2>
        <p>This page is formatted for printing. When you click Print/Save, the export will be logged automatically.</p>
        <button class="btn" id="printButton">Print / Save as PDF</button>
        <a class="btn" href="admin_users.php" style="background-color: #6c757d;">Back to User Management</a>
    </div>

    <h1>TrafAnalyz User Management Report</h1>
    
    <div class="header-info">
        <p>Generated on: <?php echo date('Y-m-d H:i:s'); ?></p>
        <p>Generated by: <?php echo isset($_SESSION['username']) ? $_SESSION['username'] : 'Administrator'; ?></p>
    </div>
    
    <div class="stats">
        <h2>User Statistics</h2>
        <div class="stat-item"><strong>Total Users:</strong> <?php echo $totalUsers; ?></div>
        <div class="stat-item"><strong>Active Users:</strong> <?php echo $activeUsers; ?></div>
        <div class="stat-item"><strong>Suspended Users:</strong> <?php echo $suspendedUsers; ?></div>
    </div>
    
    <h2>User Accounts</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $user['UserID']; ?></td>
                <td><?php echo htmlspecialchars($user['Username']); ?></td>
                <td><?php echo htmlspecialchars($user['Email']); ?></td>
                <td><?php echo $user['Role']; ?></td>
                <td>
                    <span class="badge badge-<?php echo strtolower($user['AccountStatus']); ?>">
                        <?php echo $user['AccountStatus']; ?>
                    </span>
                </td>
                <td><?php echo date('Y-m-d', strtotime($user['CreatedAt'])); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <?php include 'admin_footer.php'; ?>
    
    <script>
    // Handle export with logging
    document.getElementById('printButton').addEventListener('click', function() {
        // Log the export action first
        fetch('export_users_pdf.php?export=1', {
            method: 'GET'
        }).then(response => {
            // Generate filename for PDF
            const today = new Date();
            const dateStr = today.getFullYear() + '-' + 
                          String(today.getMonth() + 1).padStart(2, '0') + '-' +
                          String(today.getDate()).padStart(2, '0');
            const filename = 'TrafAnalyz_User_Report_' + dateStr + '.pdf';
            
            // Set the document title (will be used as default filename)
            document.title = filename;
            
            // Trigger print dialog
            window.print();
        });
    });
    </script>
</html>